name: CI/CD Pipeline para Cloud Run Deployment Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Construir Imagen Docker
    runs-on: ubuntu-latest

    steps:
      - name: Revisar repositorio
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en Google Artifact Registry
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | docker login -u _json_key --password-stdin https://us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}

      - name: Construir y publicar imagen Docker
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform linux/amd64 -t us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/latam-devsecops-images/data-api:$IMAGE_TAG -f Flask-api/Dockerfile --push Flask-api

  deploy:
    name: Desplegar en Cloud Run
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Revisar repositorio
        uses: actions/checkout@v2

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Autenticarse con Google Cloud
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | gcloud auth activate-service-account --key-file=-
          gcloud auth list
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Desplegar en Cloud Run
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          gcloud run deploy data-api \
            --image us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/latam-devsecops-images/data-api:$IMAGE_TAG \
            --region us-east4 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}

      - name: Obtener URL del servicio de Cloud Run
        id: get_url
        run: |
          CLOUD_RUN_URL=$(gcloud run services describe data-api --region us-east4 --format 'value(status.url)')
          echo "CLOUD_RUN_URL=$CLOUD_RUN_URL"
          if [ -z "$CLOUD_RUN_URL" ]; then
            echo "Error: No se pudo obtener la URL del servicio de Cloud Run"
            exit 1
          fi
          echo "::set-output name=cloud_run_url::$CLOUD_RUN_URL"
          echo "CLOUD_RUN_URL=$CLOUD_RUN_URL" >> $GITHUB_ENV

  test:
    name: Ejecutar pruebas de integración y funcionales
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Obtener URL del servicio desplegado
        run: echo "CLOUD_RUN_URL=${{ env.CLOUD_RUN_URL }}"
      
      - name: Ejecutar prueba de integración
        env:
          CLOUD_RUN_URL: ${{ env.CLOUD_RUN_URL }}
        run: |
          if [ -z "$CLOUD_RUN_URL" ]; then
            echo "Error: CLOUD_RUN_URL no está definida"
            exit 1
          fi
          for i in {1..5}; do
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$CLOUD_RUN_URL/data" || echo "000")
            if [ "$RESPONSE" -eq 200 ]; then
              echo "Prueba de integración pasada: La API devolvió HTTP 200"
              exit 0
            fi
            echo "Prueba de integración fallida: La API no devolvió HTTP 200. Reintentando en 5 segundos..."
            sleep 5
          done
          echo "Prueba de integración fallida después de 5 intentos"
          exit 1

  unit_tests:
    name: Ejecutar prueba unitaria básica
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Revisar repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Establecer variable de entorno para PROJECT_ID
        run: |
          echo "PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Instalar dependencias
        run: |
          pip install -r Flask-api/requirements.txt

      - name: Mockear BigQuery en pruebas unitarias
        run: |
          echo "Configurando mocks para pruebas unitarias"
          # Puedes agregar un mock de BigQuery aquí si es necesario.
          echo "Mocking completado"

      - name: Ejecutar prueba unitaria simple
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
        run: |
          python Flask-api/app.py &
          APP_PID=$!
          sleep 5
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8080/data || echo "000")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Error: El servidor Flask no está respondiendo correctamente"
            kill $APP_PID
            exit 1
          else
            echo "Prueba unitaria pasada: El servidor Flask está respondiendo correctamente"
            kill $APP_PID
          fi
